# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "landregistry/centos-beta"
    config.vm.network "forwarded_port", guest: 5001, host: 5001
    config.vm.network "forwarded_port", guest: 5002, host: 5002
    config.vm.hostname = "dev"
    config.vm.synced_folder "./database", "/home/vagrant/database", create: true
    config.vm.synced_folder "./frontend", "/home/vagrant/frontend", create: true
    config.vm.provision :shell, path: 'provision.sh'
end
