# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :database do |database|
        database.vm.box = "landregistry/centos-beta"
        database.vm.network "forwarded_port", guest: 5000, host: 8080
        database.vm.hostname = "database"
        database.vm.synced_folder "./database", "/home/vagrant/srv", create: true
        database.vm.provision :shell, path: 'database/provision.sh'
    end

#    config.vm.define :frontend do |frontend|
#        database.vm.box = "landregistry/centos-beta"
#        database.vm.network "forwarded_port", guest: 5000, host: 8081
#        database.vm.hostname = "frontend"
#        database.vm.synced_folder "./frontend", "/home/vagrant/srv", create: true
#        database.vm.provision :shell, path: 'frontend/provision.sh'
#    end

end
