"""empty message

Revision ID: e8d8c6f26b
Revises: None
Create Date: 2015-03-27 14:43:28.569705

"""

# revision identifiers, used by Alembic.
revision = 'e8d8c6f26b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    ### end Alembic commands ###
